# NON GRADED CHALLENGE 6

In [2]:
import numpy as np
from numpy import array

### Apakah [1 3] adalah eigenvector dari [[1 -1][6 4]] ? Jika Iya, berapakah eigenvalue-nya?

In [13]:
A = array([[1,-1],
           [6,4]])
A

array([[ 1, -1],
       [ 6,  4]])

In [14]:
A1 = array([1,3])
A1

array([1, 3])

In [15]:
A @ A1 / A1

array([-2.,  6.])

[1 3] bukan eigenvector dari [[1 -1],[6 4]]